export const SHOP_LIST_REQUEST = 'SHOP_LIST_REQUEST'
export const SHOP_LIST_SUCCESS = 'SHOP_LIST_SUCCESS'
export const SHOP_LIST_FAIL    = 'SHOP_LIST_FAIL'

export const SHOP_DETAILS_REQUEST = 'SHOP_DETAILS_REQUEST'
export const SHOP_DETAILS_SUCCESS = 'SHOP_DETAILS_SUCCESS'
export const SHOP_DETAILS_FAIL    = 'SHOP_DETAILS_FAIL' 

export const SHOP_CREATE_REVIEW_REQUEST = 'SHOP_CREATE_REVIEW_REQUEST'
export const SHOP_CREATE_REVIEW_SUCCESS = 'SHOP_CREATE_REVIEW_SUCCESS'
export const SHOP_CREATE_REVIEW_FAIL = 'SHOP_CREATE_REVIEW_FAIL'
export const SHOP_CREATE_REVIEW_RESET = 'SHOP_CREATE_REVIEW_RESET'

export const SHOP_TOP_REQUEST = 'SHOP_TOP_REQUEST'
export const SHOP_TOP_SUCCESS = 'SHOP_TOP_SUCCESS'
export const SHOP_TOP_FAIL = 'SHOP_TOP_FAIL'