const products = [
  {
    '_id': '1',
    'name': 'Bobolo',
    'image': '/images/Bobolo.png',
    'brand': 'AfroShopMe',
    'category': 'Tubercules',
    'description':'No description for now - Coming soon!',
    'rating': 4.5,
    'numReviews': 10,
    'price': 4.50,
    'countInStock': 10,
  },
  {
    '_id': '2',
    'name': 'Cacahuètes',
    'image': '/images/arachide.png',
    'brand': 'AfroShopMe',
    'category': 'Arachides',
    'description':'No description for now - Coming soon!',
    'rating': 2.5,
    'numReviews': 3,
    'price': 4.50,
    'countInStock': 18,
  },
  {
    '_id': '3',
    'name': 'Tubercules de Manioc',
    'image': '/images/manioc.png',
    'brand': 'AfroShopMe',
    'category': 'Tubercules',
    'description':'No description for now - Coming soon!',
    'rating': 4.5,
    'numReviews': 11,
    'price': 4.50,
    'countInStock': 25,
  },
  {
    '_id': '4',
    'name': 'Nkui',
    'image': '/images/nkui.png',
    'brand': 'AfroShopMe',
    'category': 'Epices',
    'description':'No description for now - Coming soon!',
    'rating': 4.0,
    'numReviews': 21,
    'price': 4.50,
    'countInStock': 5,
  },
  {
    '_id': '5',
    'name': 'Okok',
    'image': '/images/okok.png',
    'brand': 'AfroShopMe',
    'category': 'Legumes',
    'description':'No description for now - Coming soon!',
    'rating': 5.0,
    'numReviews': 13,
    'price': 4.50,
    'countInStock': 19,
  },
  {
    '_id': '6',
    'name': 'Huile de palme',
    'image': '/images/palmoil.png',
    'brand': 'AfroShopMe',
    'category': 'Oléagineux',
    'description':'No description for now - Coming soon!',
    'rating': 4.0,
    'numReviews': 18,
    'price': 4.50,
    'countInStock': 22,
  },
  {
    '_id': '7',
    'name': '4 Côtés',
    'image': '/images/tetrapleura.png',
    'brand': 'AfroShopMe',
    'category': 'Epices',
    'description':'No description for now - Coming soon!',
    'rating': 4.0,
    'numReviews': 2,
    'price': 4.50,
    'countInStock': 35,
  },
  {
    '_id': '8',
    'name': 'Igname',
    'image': '/images/yam.png',
    'brand': 'AfroShopMe',
    'category': 'Tubercules',
    'description':'No description for now - Coming soon!',
    'rating': 4.5,
    'numReviews': 15,
    'price': 4.50,
    'countInStock': 1,
  },
  {
    '_id': '9',
    'name': 'Rondelles',
    'image': '/images/rondelle.png',
    'brand': 'AfroShopMe',
    'category': 'Epices',
    'description':'No description for now - Coming soon!',
    'rating': 3.5,
    'numReviews': 20,
    'price': 4.50,
    'countInStock': 150,
  },
]

export default products

